name: Check TOTO Carryovers

on:
  schedule:
    - cron: '37 5 * * *'  # JST 14:37 → UTC 05:37
    - cron: '7 13 * * *'  # JST 22:07 → UTC 13:07
  workflow_dispatch:      # 수동 실행 허용

permissions:
  issues: write

jobs:
  carryover-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run TOTO carryover extractor
        run: python extract_toto_carryovers.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
