name: Check TOTO Carryovers

on:
  schedule:
    - cron: '37 5 * * *'  # 예: 매일 오후 2시 37분 JST
    - cron: '7 13 * * *'  # 예: 매일 오후 10시 7분 JST
  workflow_dispatch:

permissions:
  issues: write

jobs:
  carryover-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run TOTO carryover extractor
        run: python extract_toto_carryovers.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
